hydra:
  run:
    dir: ./unet-training/${now:%Y-%m-%d}/${now:%H-%M-%S}
batch_size: 8
epochs: 100
lr: 0.001
device: 'cuda:0'
workers: 8
vis_images: 20
vis_freq: 10
weights: ./weights
logs: ./logs
voc12_root: ${hydra:runtime.cwd}/../data/raw/VOCdevkit/VOC2012
train_list: ${hydra:runtime.cwd}/voc12/train_aug.txt
val_list: ${hydra:runtime.cwd}/voc12/val.txt
cls_label_path: ${hydra:runtime.cwd}/voc12/cls_labels.npy
label_dir: ${hydra:runtime.cwd}/../data/preprocessed/cv/slic/
crop_size: 512
threshold: 0.5
weight_decay: 0
init_features: 64
finetune: True
finetune_from: ${hydra:runtime.cwd}/checkpoints/v1/unet.pt